from typing import List
from pydantic import BaseModel, Field


class SourceReference(BaseModel):
    """Reference to a source used as evidence in the research report."""

    id: str = Field(..., description="Unique source identifier (e.g. 'S1', 'S2')")
    title: str = Field(..., description="Title of the source")
    url: str = Field(..., description="URL of the source")


class ResearchSection(BaseModel):
    """A section of the synthesized research report with cited sources."""

    heading: str = Field(..., description="Section heading")
    content: str = Field(..., description="Detailed content of the section")
    citations: List[str] = Field(
        default_factory=list,
        description="List of cited source IDs (e.g. ['S1', 'S2']) backing the claims in this section",
    )


class ResearchReport(BaseModel):
    """Structured research report generated by the LLM."""

    title: str = Field(..., description="Title of the research report")
    summary: str = Field(..., description="Executive summary of research findings")
    sections: List[ResearchSection] = Field(
        default_factory=list,
        description="Structured sections detailing the research evidence and findings",
    )
    sources: List[SourceReference] = Field(
        default_factory=list,
        description="List of all sources available as evidence for this report",
    )
