from typing import List, Optional
from pydantic import BaseModel, Field, field_validator

from app.schemas.document import Document
from app.schemas.planner import ResearchPlan
from app.schemas.report import ResearchReport


class SourceItem(BaseModel):
    title: str = Field(..., description="Title of the source document or webpage")
    url: str = Field(..., description="Canonical URL of the source")
    content: str = Field(..., description="Snippet or content summary of the source")
    score: Optional[float] = Field(default=None, description="Relevance score if provided by search provider")


class ResearchRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        description="The research question to investigate",
        json_schema_extra={"example": "What are the latest breakthroughs in fusion energy?"},
    )

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Research question cannot be empty or whitespace only")
        return v.strip()


class ResearchResponse(BaseModel):
    session_id: Optional[str] = Field(
        default=None,
        description="Persisted research session UUID string",
    )
    question: str = Field(
        ...,
        description="The research question that was submitted",
    )
    status: str = Field(
        default="completed",
        description="Status of the research request (e.g. 'completed', 'error')",
    )
    plan: Optional[ResearchPlan] = Field(
        default=None,
        description="Decomposed research plan containing focused sub-questions",
    )
    sources: List[SourceItem] = Field(
        default_factory=list,
        description="List of structured web sources collected for the research question",
    )
    documents: List[Document] = Field(
        default_factory=list,
        description="List of cleaned and extracted documents from web sources",
    )
    report: Optional[ResearchReport] = Field(
        default=None,
        description="Structured research report with citations generated by LLM",
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional informational message or status summary",
    )
